### ISSUE TITLE
Maven is a missing dependency on the host

### ISSUE THREAD

**Issue by ericzolf** [Maarc/ansible_middleware_soe#5]
As the subject says, there is a call on localhost of 'mvn' in roles/java-demo-app/tasks/main.yml and it is not documented as prerequisite.

**Comment by ericzolf** [comment]
Not exactly the same error but a follow-up, once Maven is installed, the following error appears (reproduced directly on the command line):

```
$ mvn -T 4 clean package -f /tmp/mw_repo/java_apps/code/tm/demo
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/tmp/mw_repo/java_apps/code/tm/demo) has 1 error
[ERROR]     Non-readable POM /tmp/mw_repo/java_apps/code/tm/demo: /tmp/mw_repo/java_apps/code/tm/demo (Is a directory)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

Once adding `/pom.xml` to the path, it works. It might be due to an older version of Maven but I didn't check. Version on RHEL 7 is Apache Maven 3.0.5 (Red Hat 3.0.5-16).

**Comment by Maarc** [comment]
This is solved now. Thank you very much for your contribution!
